language: go
sudo: false
services: [docker]

matrix:
  include:
    - os: linux
      go: 1.14.x

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; fi
  - make dist

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

deploy:
  provider: releases
  api_key:
    secure: eu0sKgZn1mdZk56M9+m5DRzWjMQCSVxQ4uTbo0KYbPUNxWsFJak0Ra0wMYJMw87S+40kfNgSBCGDhmugHDh82Ds4yvHN8eQLt1LZi5AwvWHR+1Nm/Evj0JYVywOaWnHktrcy7CqosLILlrrSVF13JHSTAs17lA4SdPTSVyEhDe8N1XN5MENu0HzL21xR37rL5cdjDtxoGTaY+VKAGHAl4/WMbaQBJWSQX6zzMOp22iLl27dL/L3FmCE2PufgaYfGjBLBlA18BksEY3foDUK9GAoSpnIEsbt9uNia/dkMFevAOwNfkW0ZG2Szmi3Rs1oCOUEcg7rbsgmVYajVbZvMXlVky6El7otwK+9659SZurTAJ9ZDt/d8wnM8pcTdcqXWn09ZSrJLdRYyQAWOwb6JY32Z/ux91byYdaMSQ1OxrKnMfnoXZVavO8yAlH6WM0fVUzjuwl54RmhTUFurdRPoXfgMiwbZBwhjDAXAMmYDQ6s+4JBTGrZNI7tmTDY1iB2S5mHET6PNLbxKQaCrKkfkhMfiX2SIVNENIEMefcbREJekgn1Fb7midLTrVwUr11EfaUhqPnGdasF6RrOG9Hn9yA/VBCxtBkc/jCUTJ4TWqRyqypMavQ2G83G6C6W6DmU5U3Y49hVumUxHUt1fI3T16Xvobo3oepS6GixU1EweZ0g=
  file_glob: true
  file:
    - bin/imagecashletter-*
    - bin/imagecashletter.exe
  on:
    repo: moov-io/imagecashletter
    tags: true
    go: 1.14.x
  skip_cleanup: true

notifications:
  slack:
    secure: gZBYPH1MBi4D8Hq+knLt4NmaRwQwmyddVRX3/EVpg0teQuZr1pjuM8EV2EeKWZ4saurj4tAX4vEdEmAu+oT5vfqYiUxGbGqphtEx52wdpRHuRXHx58p04/hqg2M5iqMz2rFgkPtM2iNwC+fpzzyQ7DTYY4Iua/eF9cxb8NsshCBuVFWcg+z8vZfTzQvKnT2UkekoOL1VQ0bAc97//1a7cXkr/GPhyUGCzt9KUgCFnB5PE0je/fwWF27fV/FiuaQZ/cHFCFQkWdcp7zEwjPkDXrDx7gIAYYsje9OB5hNSRYE8UZiddKUjmb60YAQxmO7cms/9XnmCZKifsYZzeMCHujLzOT+Cy21yRghM5HfTHUxhm/MANPY5hxkrd511nXAs5IfyhS9ZmxhA+WPo5bzpcIimGbxv1Fc6cBh5zvIN4vPLGDpvZR9DaxqHJ0WfiHW85abqsPuiCW12oY4WZkD1Kbs0OsJLEeMWrIICgD4CoHkUJTeUQSnQDguNcK/yvtnih8E9BtcxjU9IrJ5sIQ+UJvptvLf30QIFDqeJ2di3L4vuop7fqDNGtI5L0V6YFoxME1ddguDRrn655qLnmWOXHO3vAXQIIdfidkG/kYZXASuQezfqCn1f9fRWjB/2RDdKPyYPJ1YQl7bCdAuyq36CRzt7Kb523f40K4XmaLsE13M=
